import { ROUTE_ARGS_METADATA } from '@nestjs/common/constants';

export const GRAMMY_MODULE_OPTIONS = 'GRAMMY_MODULE_OPTIONS';
export const GRAMMY_BOT_NAME = 'GRAMMY_BOT_NAME';
export const DEFAULT_BOT_NAME = 'DEFAULT_BOT_NAME';
export const UPDATE_METADATA = 'UPDATE_METADATA';
export const LISTENERS_METADATA = 'LISTENERS_METADATA';
export const COMMAND_METADATA = 'COMMAND_METADATA';
export const COMPOSER_METADATA = 'COMPOSER_METADATA';
export const PARAM_ARGS_METADATA = ROUTE_ARGS_METADATA;
